In [1]:
import numpy as np

In [2]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
mat[3,4]

20

In [53]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [55]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [56]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
sum(sum(mat))

325

In [62]:
np.std(mat)

7.211102550927978

In [63]:
sum(mat)

array([55, 60, 65, 70, 75])